In [1]:
#Numpy

In [2]:
conda install numpy


Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\sravani\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.10.1               |   py38haa95532_1         2.9 MB
    ------------------------------------------------------------
                                           Total:         2.9 MB

The following packages will be UPDATED:

  conda                                4.9.2-py38haa95532_0 --> 4.10.1-py38haa95532_1




conda-4.10.1         | 2.9 MB    |            |   0% 
conda-4.10.1         | 2.9 MB    |            |   1% 
conda-4.10.1         | 2.9 MB    | #9         |  19% 
conda-4.10.1         | 2.9 MB    | ######4    |  65% 
conda-4.10.1         | 2.9 MB    | ########## | 100% 
conda-4.10.1         | 2.9 MB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying t

In [4]:
import numpy as np

In [5]:
my_lst = [1,2,34,5,6,4]
arr = np.array(my_lst)

In [6]:
type(arr)

numpy.ndarray

In [7]:
print(arr)

[ 1  2 34  5  6  4]


In [8]:
my_lst1 = [6,4,8,2,5]
my_lst2 = [8,3,2,6,8]
my_lst3 = [4,2,0,2,1]
arr = np.array([my_lst1,my_lst2,my_lst3])

In [9]:
print(arr)

[[6 4 8 2 5]
 [8 3 2 6 8]
 [4 2 0 2 1]]


In [10]:
arr.shape

(3, 5)

In [11]:
arr.reshape(5,3)

array([[6, 4, 8],
       [2, 5, 8],
       [3, 2, 6],
       [8, 4, 2],
       [0, 2, 1]])

In [12]:
arr.reshape(1,15)

array([[6, 4, 8, 2, 5, 8, 3, 2, 6, 8, 4, 2, 0, 2, 1]])

In [13]:
# Accessing array elements
arr = np.array([4,6,2,9,0,7,5,4,3,2,8,7])

In [14]:
arr[5]

7

In [16]:
my_lst1 = [6,8,2,5]
my_lst2 = [8,3,42,6]
my_lst3 = [4,2,0,2]
arr = np.array([my_lst1,my_lst2,my_lst3])

In [17]:
print(arr)

[[ 6  8  2  5]
 [ 8  3 42  6]
 [ 4  2  0  2]]


In [20]:
arr[1:,1:3]

array([[ 3, 42],
       [ 2,  0]])

In [18]:
arr[1:,3:]

array([[6, 8],
       [2, 1]])

In [20]:
arr[1:,2:4]

array([[2, 6],
       [0, 2]])

In [21]:
arr[1:2,1:4]

array([[3, 2, 6]])

In [28]:
arr = np.arange(0,10,2)

In [29]:
arr

array([0, 2, 4, 6, 8])

In [21]:
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [39]:
arr[3:]=100

TypeError: can only assign an iterable

In [40]:
arr

[1, 3, 2, 54, 2, 8, 9, 6, 4]

In [41]:
arr [3:] =100

TypeError: can only assign an iterable

In [42]:
# copy and broadcasting
arr = np.array([4,6,2,9,0,7,5,4,3,2,8,7])

In [43]:
arr[3:]=100

In [44]:
arr

array([  4,   6,   2, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [45]:
arr1 = arr

In [46]:
arr1[3:]=500

In [47]:
arr1

array([  4,   6,   2, 500, 500, 500, 500, 500, 500, 500, 500, 500])

In [48]:
arr

array([  4,   6,   2, 500, 500, 500, 500, 500, 500, 500, 500, 500])

In [49]:
arr1 = arr.copy()

In [50]:
arr1[3:] =1000

In [51]:
arr

array([  4,   6,   2, 500, 500, 500, 500, 500, 500, 500, 500, 500])

In [53]:
arr1

array([   4,    6,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000])

In [54]:
# some conitions which are useful in exploratory data analysis

In [55]:
val = 2
arr*2

array([   8,   12,    4, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000])

In [56]:
arr/4

array([  1. ,   1.5,   0.5, 125. , 125. , 125. , 125. , 125. , 125. ,
       125. , 125. , 125. ])

In [57]:
arr<2

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [59]:
arr[arr<200]

array([4, 6, 2])